const {test}=require('node:test');
const assert=require('node:assert/strict');
const {createHash}=require('node:crypto');
const {makeHandler}=require('./manual-orders.cjs');
const admin='test-owner-access-key-never-used-in-production';
Object.assign(process.env,{MANUAL_CHECKOUT_ENABLED:'true',DATABASE_URL:'postgresql://local/test',MANUAL_PAYMENT_NUMBER:'01781999032',STORE_SUPPORT_EMAIL:'test@example.invalid',ORDER_TOKEN_SECRET:'unit-test-only-secret-do-not-deploy-123456',ORDER_ADMIN_KEY_SHA256:createHash('sha256').update(admin).digest('hex'),STORE_SIZES:'M,L'});
function setup(){
 const orders=new Map();
 const db={ping:async()=>{},rate:async()=>1,create:async o=>{if(!orders.has(o.id))orders.set(o.id,structuredClone(o));return structuredClone(orders.get(o.id));},get:async id=>structuredClone(orders.get(id)),list:async()=>[...orders.values()].map(o=>structuredClone(o)),submit:async(id,tx,now)=>{const o=orders.get(id);if(o.status!=='awaiting_payment')return o.transactionId===tx?structuredClone(o):'LOCKED';if([...orders.values()].some(v=>v.method===o.method&&v.transactionId===tx))return 'DUPLICATE';Object.assign(o,{status:'awaiting_verification',transactionId:tx,submittedAt:now});return structuredClone(o);},review:async(id,status)=>{const o=orders.get(id);if(o.status!=='awaiting_verification')return 'LOCKED';o.status=status;return structuredClone(o);}};
 const handler=makeHandler(db);
 const call=async(body,headers={})=>{let status,result;await handler({method:'POST',headers:{'content-type':'application/json',origin:'https://www.aestrelaglobal.com',...headers},body},{setHeader(){},status(n){status=n;return this;},json(data){result=data;return this;}});return {status,...result};};
 return {call,db,orders};
}
const order=(requestId='a'.repeat(32))=>({action:'create',requestId,method:'bkash',customer:{name:'Test Customer',phone:'01700000000',address:'TEST ONLY, no shipment address',district:'Dhaka'},items:[{id:'be-cool',quantity:1,size:'M',price:1}]});
test('server prices override client input; phone only after durable create; idempotent retry',async()=>{const {call,orders}=setup();const config=await call({action:'config'});assert.equal(config.enabled,true);assert.equal(config.paymentNumber,undefined);const a=await call(order());assert.equal(a.status,200);assert.equal(a.order.total,10);assert.equal(a.order.paymentNumber,'01781999032');assert.equal(a.order.customer,undefined);assert.equal(a.order.tokenHash,undefined);const b=await call(order());assert.equal(b.order.id,a.order.id);assert.equal(b.token,a.token);assert.equal(orders.size,1);const changed=order();changed.items[0].quantity=2;assert.equal((await call(changed)).status,409);});
test('invalid sizes, quantities, products, provider and shipping details rejected',async()=>{const {call}=setup();for(const mutate of [o=>o.items[0].size='XX',o=>o.items[0].quantity=-1,o=>o.items[0].id='unknown',o=>o.method='cash',o=>o.customer.phone='invalid',o=>o.items.push(o.items[0])]){const o=order();mutate(o);assert.equal((await call(o)).status,400);}});
test('order access requires private token',async()=>{const {call}=setup();const a=await call(order());assert.equal((await call({action:'status',id:a.order.id,token:'b'.repeat(64)})).status,404);assert.equal((await call({action:'list'})).status,401);});
test('submission stays pending until owner verifies; references cannot be reused',async()=>{const {call}=setup();const a=await call(order()),b=await call(order('b'.repeat(32)));const payment={action:'submit',id:a.order.id,token:a.token,transactionId:'TX12345678'};const pending=await call(payment);assert.equal(pending.order.status,'awaiting_verification');assert.equal(pending.order.paymentNumber,undefined);assert.equal((await call(payment)).status,200);assert.equal((await call({...payment,id:b.order.id,token:b.token})).status,409);assert.equal((await call({action:'review',id:a.order.id,status:'paid',confirmed:true})).status,401);assert.equal((await call({action:'review',id:a.order.id,status:'paid',confirmed:false},{authorization:'Bearer '+admin})).status,400);assert.equal((await call({action:'review',id:a.order.id,status:'paid',confirmed:true},{authorization:'Bearer '+admin})).order.status,'paid');});
test('owner list strips token hashes',async()=>{const {call}=setup();await call(order());const result=await call({action:'list'},{authorization:'Bearer '+admin});assert.equal(result.orders[0].customer.name,'Test Customer');assert.equal(result.orders[0].tokenHash,undefined);});
test('storage outage never exposes recipient number',async()=>{const {call,db}=setup();db.create=async()=>{throw Error('Database down');};const result=await call(order());assert.equal(result.status,503);assert.equal(result.order,undefined);});
test('cross-origin and rate-limited requests rejected',async()=>{const {call,db}=setup();assert.equal((await call(order(),{origin:'https://untrusted.invalid'})).status,403);db.rate=async()=>121;assert.equal((await call(order())).status,429);});
test('missing production configuration fails closed',async()=>{const {call}=setup();const original=process.env.MANUAL_CHECKOUT_ENABLED;process.env.MANUAL_CHECKOUT_ENABLED='false';try{assert.equal((await call({action:'config'})).enabled,false);assert.equal((await call(order())).status,503);}finally{process.env.MANUAL_CHECKOUT_ENABLED=original;}});
test('all six products can be checked out with server prices and free delivery',async()=>{const {call}=setup();const body=order();body.method='nagad';body.items=require('../storefront/catalog.json').map(p=>({id:p.id,size:'M',quantity:2,price:0}));const result=await call(body);assert.equal(result.status,200);assert.equal(result.order.items.length,6);assert.equal(result.order.total,6010);assert.equal(result.order.shipping,0);assert.equal(result.order.testMode,false);});
test('unpublished sizes are captured as requests, not invented availability',async()=>{const {call}=setup();const original=process.env.STORE_SIZES;process.env.STORE_SIZES='';try{const body=order();body.items[0].size='XL';const result=await call(body);assert.equal(result.status,200);assert.equal(result.order.items[0].sizeNeedsConfirmation,true);body.requestId='c'.repeat(32);body.items[0].size='<script>';assert.equal((await call(body)).status,400);}finally{process.env.STORE_SIZES=original;}});
test('legacy test environment cannot replace the customer cart',async()=>{const {call}=setup();process.env.STORE_CHECKOUT_MODE='test';try{const body=order();body.items=[{id:'spider-man',quantity:3,size:'L'}];const result=await call(body);assert.equal(result.order.total,1797);assert.equal(result.order.items[0].id,'spider-man');assert.equal(result.order.testMode,false);}finally{delete process.env.STORE_CHECKOUT_MODE;}});
